package com.mycompany.wechat.modelo;
// Generated 06-abr-2016 11:05:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Archivo generated by hbm2java
 */
public class Archivo  implements java.io.Serializable {


     private Integer idArchivo;
     private String tipo;
     private String ruta;
     private Date fecha;
     private Set mensajes = new HashSet(0);

    public Archivo() {
    }

	
    public Archivo(String tipo, String ruta, Date fecha) {
        this.tipo = tipo;
        this.ruta = ruta;
        this.fecha = fecha;
    }
    public Archivo(String tipo, String ruta, Date fecha, Set mensajes) {
       this.tipo = tipo;
       this.ruta = ruta;
       this.fecha = fecha;
       this.mensajes = mensajes;
    }
   
    public Integer getIdArchivo() {
        return this.idArchivo;
    }
    
    public void setIdArchivo(Integer idArchivo) {
        this.idArchivo = idArchivo;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getRuta() {
        return this.ruta;
    }
    
    public void setRuta(String ruta) {
        this.ruta = ruta;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }




}


