package com.mycompany.wechat.modelo;
// Generated 06-abr-2016 11:05:56 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Conversacion generated by hbm2java
 */
public class Conversacion  implements java.io.Serializable {


     private int idConversacion;
     private String nombre;
     private Date fecha;
     private int numParticipantes;
     private Set mensajes = new HashSet(0);
     private Set usuarioTieneConversacions = new HashSet(0);

    public Conversacion() {
    }

	
    public Conversacion(int idConversacion, String nombre, Date fecha, int numParticipantes) {
        this.idConversacion = idConversacion;
        this.nombre = nombre;
        this.fecha = fecha;
        this.numParticipantes = numParticipantes;
    }
    public Conversacion(int idConversacion, String nombre, Date fecha, int numParticipantes, Set mensajes, Set usuarioTieneConversacions) {
       this.idConversacion = idConversacion;
       this.nombre = nombre;
       this.fecha = fecha;
       this.numParticipantes = numParticipantes;
       this.mensajes = mensajes;
       this.usuarioTieneConversacions = usuarioTieneConversacions;
    }
   
    public int getIdConversacion() {
        return this.idConversacion;
    }
    
    public void setIdConversacion(int idConversacion) {
        this.idConversacion = idConversacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public int getNumParticipantes() {
        return this.numParticipantes;
    }
    
    public void setNumParticipantes(int numParticipantes) {
        this.numParticipantes = numParticipantes;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }
    public Set getUsuarioTieneConversacions() {
        return this.usuarioTieneConversacions;
    }
    
    public void setUsuarioTieneConversacions(Set usuarioTieneConversacions) {
        this.usuarioTieneConversacions = usuarioTieneConversacions;
    }




}


