package com.mycompany.wechat.modelo;
// Generated 06-abr-2016 11:05:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Mensaje generated by hbm2java
 */
public class Mensaje  implements java.io.Serializable {


     private Integer idMensaje;
     private Archivo archivo;
     private Conversacion conversacion;
     private Usuario usuario;
     private String texto;
     private Date fecha;

    public Mensaje() {
    }

    public Mensaje(Archivo archivo, Conversacion conversacion, Usuario usuario, String texto, Date fecha) {
       this.archivo = archivo;
       this.conversacion = conversacion;
       this.usuario = usuario;
       this.texto = texto;
       this.fecha = fecha;
    }
   
    public Integer getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(Integer idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Archivo getArchivo() {
        return this.archivo;
    }
    
    public void setArchivo(Archivo archivo) {
        this.archivo = archivo;
    }
    public Conversacion getConversacion() {
        return this.conversacion;
    }
    
    public void setConversacion(Conversacion conversacion) {
        this.conversacion = conversacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getTexto() {
        return this.texto;
    }
    
    public void setTexto(String texto) {
        this.texto = texto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


