package com.mycompany.wechat.modelo;
// Generated 06-abr-2016 11:05:56 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String correo;
     private String clave;
     private String usuario;
     private String admin;
     private Set usuarioTieneConversacions = new HashSet(0);
     private Set mensajes = new HashSet(0);

    public Usuario() {
    }
    
    public Usuario(String correo, String clave, String usuario, String admin) {
        this.correo = correo;
        this.clave = clave;
        this.usuario = usuario;
        this.admin = admin;
    }
    public Usuario(String correo, String clave, String usuario, String admin, Set usuarioTieneConversacions, Set mensajes) {
       this.correo = correo;
       this.clave = clave;
       this.usuario = usuario;
       this.admin = admin;
       this.usuarioTieneConversacions = usuarioTieneConversacions;
       this.mensajes = mensajes;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getAdmin() {
        return this.admin;
    }
    
    public void setAdmin(String admin) {
        this.admin = admin;
    }
    public Set getUsuarioTieneConversacions() {
        return this.usuarioTieneConversacions;
    }
    
    public void setUsuarioTieneConversacions(Set usuarioTieneConversacions) {
        this.usuarioTieneConversacions = usuarioTieneConversacions;
    }
    public Set getMensajes() {
        return this.mensajes;
    }
    
    public void setMensajes(Set mensajes) {
        this.mensajes = mensajes;
    }

    @Override
    public String toString() {
        return "Usuario{" + "idUsuario=" + idUsuario + ", correo=" + correo + ", clave=" + clave + ", usuario=" + usuario + ", admin=" + admin + ", usuarioTieneConversacions=" + usuarioTieneConversacions + ", mensajes=" + mensajes + '}';
    }




}


