package com.mycompany.wechat.modelo;
// Generated 06-abr-2016 11:05:56 by Hibernate Tools 4.3.1



/**
 * UsuarioTieneConversacion generated by hbm2java
 */
public class UsuarioTieneConversacion  implements java.io.Serializable {


     private UsuarioTieneConversacionId id;
     private Conversacion conversacion;
     private Usuario usuario;

    public UsuarioTieneConversacion() {
    }

    public UsuarioTieneConversacion(UsuarioTieneConversacionId id, Conversacion conversacion, Usuario usuario) {
       this.id = id;
       this.conversacion = conversacion;
       this.usuario = usuario;
    }
   
    public UsuarioTieneConversacionId getId() {
        return this.id;
    }
    
    public void setId(UsuarioTieneConversacionId id) {
        this.id = id;
    }
    public Conversacion getConversacion() {
        return this.conversacion;
    }
    
    public void setConversacion(Conversacion conversacion) {
        this.conversacion = conversacion;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }




}


